# Generated by Django 4.1.3 on 2022-12-03 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusname', models.CharField(max_length=100)),
                ('campuslocation', models.CharField(max_length=50)),
                ('campuslogo', models.ImageField(upload_to='properties/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floortype', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth'), ('5th', 'Fifth')], max_length=10)),
                ('roomType', models.CharField(choices=[('HOSTEL', 'hostel'), ('HOMESTEL', 'homestel')], max_length=10)),
                ('apartmentName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('apartmentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('persons', models.CharField(choices=[('1 in 1', 'one in one'), ('2 in 1', 'Two in one'), ('3 in 1', 'Three in one'), ('4 in 1', 'Four in one')], max_length=100)),
                ('description', models.TextField()),
                ('apartmentImage', models.ImageField(upload_to='properties/images/')),
                ('room1', models.ImageField(upload_to='properties/images/')),
                ('room2', models.ImageField(upload_to='properties/images/')),
                ('room3', models.ImageField(upload_to='properties/images/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties_app.campuscategory')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.book')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.room')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.customer'),
        ),
    ]
