# Generated by Django 4.1.3 on 2022-12-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='apartmentUrl',
            field=models.URLField(default=None, null=True),
        ),
    ]
