# Generated by Django 3.2.12 on 2022-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0015_remove_payment_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuscategory',
            name='campuslogo',
            field=models.URLField(default=None, null=True),
        ),
    ]
