# Generated by Django 3.2.12 on 2022-12-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0016_alter_campuscategory_campuslogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room1',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room2',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room3',
            field=models.URLField(default=None, null=True),
        ),
    ]
